apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: default
type: Opaque
data:
    mysql-root-password: ENC[AES256_GCM,data:ypR1OpKjksecqh0crztoxbhrWNw=,iv:T+IAIAsmIxpC8cyXLdfQncvM3zUM8t7NWzd4ryVlHPk=,tag:SF5oCORKjFJmnZ9+43QEfw==,type:str]
    mysql-user: ENC[AES256_GCM,data:RA9G2R78ctQJPuxGrnEQClNKZkM=,iv:aPYkToNCw2MvzELi7hZntpe3XRNZqfieeZ9T/bD1am8=,tag:sR6ryOaIj6nrBRUlUjYW5Q==,type:str]
    mysql-password: ENC[AES256_GCM,data:KJUhIdfUWP15RTKjh7vwtZiZQRU=,iv:nolQ5F51DNeV2/DkRtRb0YqbdgmzmxcFjBzJZEnLtDA=,tag:0rlU/Jl6/VL6hU66hdmb3w==,type:str]
    mysql-database: ENC[AES256_GCM,data:QB0SkARrbIVCQQRh,iv:LlfNnbWf5mVQjgGjBPlfiYIuBhjoMQl1RZdrOwL6YjQ=,tag:dSaJxkYmIZeg+VIfGEMELg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hg0t04trc098c3krn656dqtgkkzh6tecaml9qx89ln3fhv8eaf0s2ldn8u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dkVCcFFzUDc0QzJhMllq
            V0tiTmNhb0hMU0tIbWZlVFZZUnBUY3FPMGc0CkxkbTFUajFkWUxXSmZ0Rk1JOURi
            MC8yRGo0RTRwT3l6OVM1KzNiL2FMWUkKLS0tICt1enp2TnVDemJlYWZkdEs4UXVM
            NjNOQ29iQnRiOTlYYnEra3MxYTdJWjQKwqJFLdJjktDNkirLKFoFYe9EU3Lm5Tsr
            Eu2TnP/rYO84HiOnjTA43cvfZD3oHNVnz71h6FVGUBLIuJB66wBRuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-14T12:12:21Z"
    mac: ENC[AES256_GCM,data:dxPJYVBuk9OwuhAluh/PILDBldsbDrZrbSNzKYgC5ieWR24En10+MytODIyHsIjo54pNxN9K1byItzW5lJo0W2YFnd1Azb9zS0qxXrLW8iXXoHMr/2WSzNP0d25m+oyzga2m0db16TWiyftWU8cxBxKlR92gH+aKbQTlymyX8/w=,iv:Lg5GikqZVtrL7MUllES3WmKnyiR59Wjz0DLyknH2oJM=,tag:zX86c73m2gKHxshBYiQytg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
