apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  releaseName: promtail
  targetNamespace: monitoring
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: "6.15.5"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    config:
      logLevel: info
      serverPort: 3101
      clients:
        - url: http://loki:3100/loki/api/v1/push
      
    # Scrape configuration for various log sources
    extraScrapeConfigs:
      - job_name: containers
        static_configs:
          - targets:
              - localhost
            labels:
              job: containerlogs
              __path__: /var/log/containers/*log
        pipeline_stages:
          - json:
              expressions:
                output: log
                stream: stream
                attrs:
          - json:
              source: attrs
              expressions:
                tag:
          - regex:
              source: tag
              expression: '^.+?\.(?P<container_name>.+?)\..+?$'
          - timestamp:
              source: time
              format: RFC3339Nano
          - labels:
              stream:
              container_name:
          - output:
              source: output
    
    # Mount log paths
    extraVolumes:
      - name: containers
        hostPath:
          path: /var/log/containers
      - name: pods
        hostPath:
          path: /var/log/pods
    
    extraVolumeMounts:
      - name: containers
        mountPath: /var/log/containers
        readOnly: true
      - name: pods
        mountPath: /var/log/pods  
        readOnly: true
    
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3