apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system  # Must be in flux-system for FluxCD to manage
spec:
  releaseName: metallb
  targetNamespace: metallb-system  # Where MetalLB pods will be deployed
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "0.13.12"
      sourceRef:
        kind: HelmRepository 
        name: metallb
        namespace: flux-system 
  values:
    controller:
      image:
        tag: v0.13.12
    speaker:
      image:
        tag: v0.13.12
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3