apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  releaseName: loki
  targetNamespace: monitoring
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "6.6.4"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    deploymentMode: SingleBinary
    
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            index:
              prefix: loki_index_
              period: 24h
            object_store: filesystem
            schema: v13
    
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: local-path
        size: 10Gi
      
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
      
    lokiCanary:
      enabled: false
      
    test:
      enabled: false
      
    monitoring:
      serviceMonitor:
        enabled: true
        labels:
          release: prometheus
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3