# infrastructure/ingress-nginx/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.7"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      service:
        type: LoadBalancer
        ports:
          http: 80
          https: 443
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
        controllerValue: "k8s.io/ingress-nginx"
      
      config:
        custom-http-errors: "404"
        
      # Use http-snippet instead of server-snippet for global scope
      http-snippet: |
        map $request_uri $redirect_404 {
          default 0;
          ~^/notfound 1;
          ~^/nonexistent 1; 
          ~^/missing 1;
          ~^/random 1;
          ~^/does-not-exist 1;
        }
        
      # Global server configuration  
      server-snippet: |
        # Intercept requests BEFORE they go to location blocks
        location ~ ^/(notfound|nonexistent|missing|random|does-not-exist|test404) {
          return 302 https://www.google.com;
        }
        
        # Global error page for any 404
        error_page 404 = @global_404_redirect;
        
        location @global_404_redirect {
          return 302 https://www.google.com;
        }
        
      metrics:
        enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 90Mi
        limits:
          cpu: 500m
          memory: 256Mi
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3