# infrastructure/ingress-nginx/helmrelease-simple.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.7"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      service:
        type: LoadBalancer
        ports:
          http: 80
          https: 443
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
        controllerValue: "k8s.io/ingress-nginx"
      
      # Enable snippets
      enableSnippets: true
      allowSnippetAnnotations: true
      
      config:
        custom-http-errors: "404"
        allow-snippet-annotations: "true"
        
      # Simple 404 redirect without Lua complexity
      server-snippet: |
        # Global 404 error handler
        error_page 404 = @redirect_404_to_google;
        
        location @redirect_404_to_google {
          return 302 https://www.google.com;
        }
        
      metrics:
        enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 90Mi
        limits:
          cpu: 500m
          memory: 256Mi
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3