apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-404-redirect
  namespace: ingress-nginx
data:
  404-redirect.lua: |
    local function redirect_404_to_google()
      -- Check if the response status is 404
      if ngx.status == 404 then
        -- Redirect to google.com
        ngx.redirect("https://www.google.com", 302)
      end
    end
    
    -- Execute the redirect function
    redirect_404_to_google()