# infrastructure/ingress-nginx/lua-plugin.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-404-redirect
  namespace: ingress-nginx
data:
  404-redirect.lua: |
    -- Global 404 redirect handler
    -- This script will redirect ANY 404 response to google.com
    
    local function handle_404_redirect()
      -- Check if we got a 404 response
      if ngx.status == 404 then
        -- Log the redirect for debugging
        ngx.log(ngx.ERR, "Redirecting 404 request for: " .. ngx.var.request_uri .. " to google.com")
        
        -- Perform the redirect
        return ngx.redirect("https://www.google.com", 302)
      end
    end
    
    -- Execute the handler
    handle_404_redirect()